### ISSUE TITLE
Listen for keys

### ISSUE THREAD

**Issue by dennischrist** [cMadan/ElGateau#1]
Hi Christopher,

hope you are fine.

Just found your git for streamdeck and was wondering how far you are with the listeners for the keys,

it says that is not yet implemented! Hope you have some good news! ;)

**Comment by cMadan** [comment]
Yes, the button listening is working, though the package as a whole is still very much in development. The functions you should look at are `ElGateau.button_listen_key` and `ElGateau.button_getch`.
